AWSTemplateFormatVersion: "2010-09-09"
Description: sampleee

Parameters: 
  SsoInsanceId: 
    Type: String
    Description: 'xxxxxxxxxxxxxxxx from arn:aws:sso:::instance/ssoins-xxxxxxxxxxxxxxxx'
  SecurityAccountId:
    Type: String
  LogAccountId:
    Type: String
  UserManagementAccountId:
    Type: String
  AllowAddress:
    Type: String
    Description: 'input like "IPAddress-1","IPAdress-2",...'
    Default: '"1.1.1.1/32","2.2.2.2/32","3.3.3.3/32"'

Resources:
# Permission Set
  OrganizationsControl:
    Type: AWS::SSO::PermissionSet
    Properties:
      Description: 'Permission set being used to manege AWS organizations services'
      SessionDuration: 'PT6H' # The length of time that the application user sessions are valid for in the ISO-8601 standard.
      InstanceArn: !Sub arn:aws:sso:::instance/ssoins-${SsoInsanceId}
      Name: 'nri-qumoa-OrganizationsControl'
      InlinePolicy:  !Sub '{
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "AllowListDesctibe",
                "Effect": "Allow",
                "Action": [
                    "organizations:ListRoots",
                    "organizations:ListDelegatedServicesForAccount",
                    "organizations:DescribeAccount",
                    "organizations:DescribePolicy",
                    "organizations:ListChildren",
                    "organizations:ListCreateAccountStatus",
                    "organizations:DescribeOrganization",
                    "organizations:DescribeOrganizationalUnit",
                    "organizations:DescribeHandshake",
                    "organizations:DescribeCreateAccountStatus",
                    "organizations:ListPoliciesForTarget",
                    "organizations:DescribeEffectivePolicy",
                    "organizations:ListTargetsForPolicy",
                    "organizations:ListTagsForResource",
                    "organizations:ListAWSServiceAccessForOrganization",
                    "organizations:ListPolicies",
                    "organizations:ListDelegatedAdministrators",
                    "organizations:ListAccountsForParent",
                    "organizations:ListHandshakesForOrganization",
                    "organizations:ListHandshakesForAccount",
                    "organizations:ListAccounts",
                    "organizations:ListParents",
                    "organizations:ListOrganizationalUnitsForParent",
                    "organizations:CreateOrganizationalUnit",
                    "organizations:CreatePolicy",
                    "organizations:MoveAccount"
                ],
                "Resource": "*"
            },
            {
                "Sid": "AllowOUSCPWrite",
                "Effect": "Allow",
                "Action": [
                    "organizations:UpdateOrganizationalUnit",
                    "organizations:DeleteOrganizationalUnit",
                    "organizations:UpdatePolicy",
                    "organizations:AttachPolicy",
                    "organizations:DetachPolicy",
                    "organizations:DeletePolicy",
                    "organizations:TagResource",
                    "organizations:UntagResource"
                ],
                "Resource": "*",
                "Condition": {
                    "StringNotEquals": {
                        "aws:ResourceTag/nri-qumoa": "managed-by-nri-qumoa"
                    }
                }
            },
            {
                "Sid": "AllowOrganizationsIntegrationFunctions",
                "Effect": "Allow",
                "Action": [
                    "health:*",
                    "trustedadvisor:*"
                ],
                "Resource": "*"
            },
            {
                "Effect": "Deny",
                "Action": "*",
                "Resource": "*",
                "Condition": {
                    "Bool": {
                        "aws:ViaAWSService": "false"
                    },
                    "NotIpAddress": {
                        "aws:SourceIP": [
                        ${AllowAddress}
                        ]
                    }
                }
            }
        ]
    }'

